# Generated by Django 4.1 on 2022-08-11 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_alter_phase_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='deleted',
        ),
    ]
