# Generated by Django 4.1 on 2022-08-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_remove_phase_date_created_remove_phase_date_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='event',
            name='deleted',
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
