# Generated by Django 4.1 on 2022-08-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_category_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
